### ISSUE TITLE
use question

### ISSUE THREAD

**Issue by Tyler0801** [VaishnavDatir/sql_conn#11]
Hello VaisnavDatir
I use this library can connect DB
But I can't use any sql command

The run result as described below

I/flutter ( 9618): dbConnect=true
I/flutter ( 9618): PlatformException(ERROR, 找不到預存程序 'nspRFLogin_GetDB_Android_Json'。, null, null)

**Comment by tjteckTyler** [comment]
Future <void> Call_SP()async{
    await SqlConn.connect(
        ip: "${IP}",
        port: "",//埠ㄅㄨˋ
        databaseName: "${DB_NAME}",
        username: "rf",
        password: "rf");
    try{
      print("dbConnect=${SqlConn.isConnected}");
    }
    catch(e){
      print("mistake+${e}");
    }

//"""exec nspRFLogin_GetDB_Android_Json '{"RFLoginData": [ {"userID":"${_account_textEditingController.text}"}]}',1,1,1 """
//"nspRFLogin_GetDB_Android_Json"
//"select * from dbo.RFFunctionProg"

    try{
      var res = await SqlConn.writeData("""exec nspRFLogin_GetDB_Android_Json '{"RFLoginData": [ {"userID":"${_account_textEditingController.text}"}]}',1,1,1 """);
      debugPrint(res.toString());
    }catch(e){
      print(e);
    }

  }

**Comment by VaishnavDatir** [comment]
Hey @tjteckTyler,
Thanks for using sql_conn plugin. Please send the query which you are trying to execute.

**Comment by Tyler0801** [comment]
Hi @VaishnavDatir 
1.
"""exec nspRFLogin_GetDB_Android_Json '{"RFLoginData": [ {"userID":"${_account_textEditingController.text}"}]}',1,1,1 """
2.
"nspRFLogin_GetDB_Android_Json"
3.
"select * from dbo.RFFunctionProg"

The query which I am trying yo execute as stated above.

**Comment by VaishnavDatir** [comment]
Hello @Tyler0801,

If your using stored procedure query, I'm not sure about it. It is something I need to check and will surely check it today itself.
But query no. 3, it should be running and produce some result. If it is giving error then it is something strange.  
But for now I can suggest you to use normal queries will soon launch another version of this plugin which consists all the required features,
