### ISSUE TITLE
 I can't connect to the server

### ISSUE THREAD

**Issue by alimimert** [VaishnavDatir/sql_conn#12]
When I run the sample project you shared on my own computer, I cannot connect.
Also, when I enter my own database information, I cannot connect.
I'll be glad, if you help me.

I get this error:
I/flutter (12291): Connecting...
I/flutter (12291): PlatformException(ERROR, Network error IOException: failed to connect to /192.168.128.176 (port 1433) from /10.0.2.16 (port 47216) after 15000ms, null, null)

**Comment by VaishnavDatir** [comment]
Hi @alimimert,
First of all thanks for using this plugin.
This plugin is strictly for SQL Server only. And runs on Android devices only.
Make sure your ADB and server are connect on same internet connection.
Also Make Sure that your SQL Server Browser service is active.
Goto AllProgram->SQL Server ->configuraton tools->SQL Server Configuration Manager->SQL Server Network Configuration-> Select your server instance and right click on TCP/IP then goto IPAddresses. Change/Place port number for all IP's as 1433. Also make sure that the IP Address is Active and Enabled. Save it and restart the server.

The error message which you have provided must not occur if your following above requirements.
If your still facing same error let me know, will look into it 👍🏻

Thankyou.

**Comment by VaishnavDatir** [comment]
Hi @alimimert,
Today I tried the error you have got.
If you have database on your local system. After completing the above commented steps. Goto firewall and add Inbound and Outbound rule for the particular port on which your SQL Server is running.

Thankyou.
