### ISSUE TITLE
Cannot connect to "localhost"

### ISSUE THREAD

**Issue by arifzain74** [VaishnavDatir/sql_conn#2]
I successfully connected to my system using ip address. But was not able to connect to a system with system name. If you are trying to connect to a sql server in your LAN, it is better to connect it using system name rather than using ip since ip address could be changed whenever the system is connected to the network again. And even I am not sure weather we can connect to sql server hosted in aws since it support only ip.

**Comment by VaishnavDatir** [comment]
Hello, right now the plugin connects to server using IP address only. Connecting to a server using name is still in development, will release this in future. For now I suggest you to connect using IP address only. And for AWS I haven't tried yet, you can try connecting using IP and if possible please share the results.

**Comment by arifzain74** [comment]
Thank you for your response. I only worked with c#.net and there we can connect either using ip address or by system name. So I thought this must be a bug. Now only I came to know it's not developed yet. So should I remove it? I highly recommend you to work on that as soon as possible..Good day, Thank you, Arif. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 19, 2022 at 10:17 PM, Vaishnav ***@***.***> wrote:   


Hello, right now the plugin connects to server using IP address only. Connecting to a server using name is still in development, will release this in future. For now I suggest you to connect using IP address only. And for AWS I haven't tried yet, you can try connecting using IP and if possible please share the results.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
