### ISSUE TITLE
Can't execute a stored procedure across a VPN

### ISSUE THREAD

**Issue by APTGithubAcct** [VaishnavDatir/sql_conn#22]
I am running a Flutter app on my physical PC and am connected to a remote server through a VPN. For some reason, it can't find a remote server that is running the SQL instance I want to connect to even though I can successfully RDP into it. Does this repo not work for servers across a VPN?

```
await SqlConn.connect(
        ip: "RemoteIP",
        port: "RemotePort",
        databaseName: "DBName",
        username: "sa",
        password: "pass");
```

Unhandled Exception: PlatformException(ERROR, Network error IOException: failed to connect to /RemoteIP (port RemotePort) from /SomeOtherIP (port SomeOtherPort) after 15000ms, null, null)

**Comment by APTGithubAcct** [comment]
Our production is halted until we can get an answer or another workaround here. Hopefully someone can answer relatively quickly. Thanks in advance!

**Comment by VaishnavDatir** [comment]
Ideally if Ip, port and other details are correct then it should be accessible. Also please check from the database side. Check DB accessibility.

Thanks

**Comment by VaishnavDatir** [comment]
Also do let me know if issue is resolved or pending.
For now closing this issue you can reopen it if required.

Thanks

**Comment by APTGithubAcct** [comment]
You can close this one
