### ISSUE TITLE
MissingPluginException (No Found for method connectDB)

### ISSUE THREAD

**Issue by kholyphoenix0** [VaishnavDatir/sql_conn#3]
Hello, 
I created 'tryCatch'.

**Example:**
```
try {
  await SqlConn.connect(ip: "xxx.xxx.xxx.xxx", port: "1433", databaseName: "database", username: "admin", password: "admin");
} catch (e) {
  debugPrint(e.toString());
}
```

Returns the following message

`
flutter: MissingPluginException(No implementation found for method connectDB on channel plugin.sqlconn.sql_conn/sql_conn)
`

**Comment by digitaleagle** [comment]
I'm getting the same error.  I'm thinking we don't have something installed.  Is there a C# wrapper, DLL, or plugin required to make this work?

**Comment by ertugrulcakici** [comment]
Just stop and rerun the project. Then it will be okey
